\documentclass[10pt]{beamer}
\usetheme{Warsaw}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage[notocbib]{apacite}
\usepackage{epstopdf}
\usepackage{booktabs}
\usepackage{colortbl, xcolor}

\setbeamertemplate{caption}{\centering\insertcaption\par}
\setlength{\belowcaptionskip}{15pt}
\renewcommand{\thetable}{}

\providecommand{\e}[1]{\ensuremath{\times 10^{#1}}}

\begin{document}


\date{}
\author{Micha\l{}  Burdukiewicz, Piotr Sobczyk}
\institute{ 
University of Wroc\l{}aw, Department of Genomics, Poland}

\title{Expanding signalHsmm using n-grams}


\begin{frame}
\maketitle

<<echo = FALSE,message=FALSE,results='asis'>>=
library(reshape2)
library(ggplot2)
library(grid)
library(biogram)
library(xtable)
library(seqinr)
library(signalHsmm)

theme_presentation <- theme(plot.background=element_rect(fill = "transparent",
                                                   colour = "transparent"),
                      plot.margin = unit(c(1,1,1,1), "cm"),
                      axis.text.x = element_text(size=7), 
                      axis.text.y = element_text(size=7),
                      axis.title.x = element_text(size=11, vjust = -1), 
                      axis.title.y = element_text(size=11, vjust = 1),
                      strip.text = element_text(size=11),
                      legend.text = element_text(size=7), 
                      legend.title = element_text(size=11),
                      plot.title = element_text(size=17),
                      panel.grid.major = element_line(colour="lightgrey", linetype = "dashed"),
                      panel.background = element_rect(fill = "transparent",colour = "black"),
                      legend.background = element_rect(fill="NA"))

@



\end{frame}

\begin{frame}
\frametitle{Outline}
\tableofcontents
\end{frame}

\section{Motivation}


\begin{frame}
To improve our model, we added few supplementary states representing specific motives that might occur in the proximity of cleavage site. The structure of cleavage sites, more conserved than other parts of signal peptide, may be reflected by n-grams (k-mers), short vectors of $n$ characters derived from input sequences.
\end{frame}

\begin{frame}
\begin{figure}[ht]\centering
\includegraphics[scale=0.42]{HSMMs}
\caption{The diagram of simple (A) and extended version of signalHsmm with the n-gram cleavage site model (B).}
\label{fig:enccomp}
\end{figure}

\end{frame}


\AtBeginSection[]
{
\begin{frame}<beamer>
\frametitle{Outline}
\tableofcontents[currentsection]
\end{frame}
}

\section{Impact of the n-gram extension}

\begin{frame}
<<echo = FALSE,message=FALSE,results='asis', fig.height=5.8>>=
load("ngram_extension.RData")

levels(plot_dat[["sig"]]) <- c("No", "Yes")

ggplot(plot_dat, aes(x=noMer,y=kMer, color=sig)) +
  geom_point() + 
  xlab("Normal model") + 
  ylab("Extended model") + 
  scale_color_discrete("Signal peptide") +
  geom_abline(slope=1) +
  theme_presentation +
  theme(legend.position="bottom")
@
\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='asis'>>=
rws <- seq(1, nrow(bench_metrics2) - 1, by = 2)
col <- rep("\\rowcolor[gray]{0.85}", length(rws))
print(xtable(bench_metrics2[, c("AUC", "TP", "TN", "FP", "FN")], "Performance of different classifiers.", digits = 4), include.rownames = TRUE, booktabs = TRUE,
      add.to.row = list(pos = as.list(rws), command = col), sanitize.text.function = identity,
      caption.placement = "top")
@
\end{frame}







\section{Greedy n-gram choosing algorithm}

\begin{frame}
bla
\end{frame}



\end{document}