\documentclass[10pt]{beamer}
\usetheme{Warsaw}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage[notocbib]{apacite}
\usepackage{epstopdf}

\setbeamertemplate{caption}{\centering\insertcaption\par}
\setlength{\belowcaptionskip}{15pt}
\renewcommand{\thetable}{}

\providecommand{\e}[1]{\ensuremath{\times 10^{#1}}}

\begin{document}


\date{}
\author{Micha\l{}  Burdukiewicz, Piotr Sobczyk}
\institute{ 
University of Wroc\l{}aw, Department of Genomics, Poland}

\title{Expanding signalHsmm using n-grams}


\begin{frame}
\maketitle

<<echo = FALSE,message=FALSE,results='asis'>>=
library(reshape2)
library(ggplot2)
library(grid)
library(biogram)
library(xtable)
library(seqinr)
library(signalHsmm)

theme_presentation <- theme(plot.background=element_rect(fill = "transparent",
                                                   colour = "transparent"),
                      plot.margin = unit(c(1,1,1,1), "cm"),
                      axis.text.x = element_text(size=7), 
                      axis.text.y = element_text(size=7),
                      axis.title.x = element_text(size=11, vjust = -1), 
                      axis.title.y = element_text(size=11, vjust = 1),
                      strip.text = element_text(size=11),
                      legend.text = element_text(size=7), 
                      legend.title = element_text(size=11),
                      plot.title = element_text(size=17),
                      panel.grid.major = element_line(colour="lightgrey", linetype = "dashed"),
                      panel.background = element_rect(fill = "transparent",colour = "black"),
                      legend.background = element_rect(fill="NA"))

@



\end{frame}

\begin{frame}
\frametitle{Outline}
\tableofcontents
\end{frame}

\section{Motivation}


\begin{frame}
To improve our model, we added few supplementary states representing specific motives that might occur in the proximity of cleavage site. The structure of cleavage sites, more conserved than other parts of signal peptide, may be reflected by n-grams (k-mers), short vectors of $n$ characters derived from input sequences.
\end{frame}

\begin{frame}
\begin{figure}[ht]\centering
\includegraphics[scale=0.42]{HSMMs}
\caption{The diagram of simple (A) and extended version of signalHsmm with the n-gram cleavage site model (B).}
\label{fig:enccomp}
\end{figure}

\end{frame}


\begin{frame}
Assumptions:
\begin{enumerate}
\item The optimal number of amino acid groups is 4.
\item Important properties are: size, polarity, charge, hydrophobicity and probability of being in the $\alpha$-chain. 
\item All properties above are equally important and distinguish signal peptides from matures proteins.
\end{enumerate}
\end{frame}

\AtBeginSection[]
{
\begin{frame}<beamer>
\frametitle{Outline}
\tableofcontents[currentsection]
\end{frame}
}


\section{Amino acid properties}

\begin{frame}
bla
\end{frame}



\end{document}